### PR TITLE
Comma value in array

### LINKED ISSUE #1102: Allow comma in array setting value
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

An array setting cannot have a comma value

### Steps to Reproduce

1. Set an array config value to `["1", ",", "2"]` in `config.cson`
2. Settings view will show '1, ,, 2'
2. Add a array item in the settings view '1, ,, 2, 3'

**Expected behavior:** 

Settings view should show '1, \,, 2'
After changing the setting `config.cson` should be `["1", ",", "2", "3"]`

**Actual behavior:** 

Settings view shows '1, ,, 2'
After changing the setting `config.cson` is `["1", "", "2", "3"]`

**Reproduces how often:**
100%

### Versions

Atom    : 1.35.0-beta0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.35.0-beta0
python 2.7.14
git 2.20.0.windows.1
visual studio 2015

### Additional Information

#1103 will fix this

### PR DESCRIPTION
**Pull request by UziTech**
### Description of the Change

`array` config type will allow an escaped comma in the value.

image

the config value will be `["1", ",", "2"]`

### Benefits

Comma can be used in array values.

### Possible Drawbacks

none

### Applicable Issues

fixes #1102
closes #1101

### CODE REVIEW

File: lib/settings-panel.js [hunk 1]
```diff
@@ -324,6 +327,15 @@ export default class SettingsPanel extends CollapsibleSectionPanel {
...
       let arrayValue = (value || '').split(',')
+      arrayValue = arrayValue.reduce((values, val) => {
+        const last = values.length - 1
+        if (last >= 0 && values[last].endsWith('\\')) {
+          values[last] = values[last].replace(/\\$/, ',') + val
+        } else {
+          values.push(val)
+        }
+        return values
+      }, [])
```
Comment (rafeca) [inline lib/settings-panel.js]: This logic is a bit convoluted, but I cannot think of a better way to do this without lookbehind regex support (I've just tried using lookbehind regexps on Atom and it seems like its Chromium version does not support them yet).

Maybe once Atom uses Electron 3 this can be refactored 😃
