### PR TITLE
Avoid throwing null pointer exceptions when package update fails

### LINKED ISSUE #766: Uncaught TypeError: Cannot read property 'substr' of null
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.0
**System**: Microsoft Windows 10 Education
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1

### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At C:\Users\Chertpong\AppData\Local\atom\app-1.7.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:709

TypeError: Cannot read property 'substr' of null
    at C:\Users\Chertpong\AppData\Local\atom\app-1.7.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:709:80
    at C:\Users\Chertpong\AppData\Local\atom\app-1.7.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:376:51
    at C:\Users\Chertpong\AppData\Local\atom\app-1.7.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:403:20
    at exit (C:\Users\Chertpong\AppData\Local\atom\app-1.7.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Chertpong\AppData\Local\atom\app-1.7.0\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\Chertpong\AppData\Local\atom\app-1.7.0\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -5:42.5.0 settings-view:open (atom-text-editor.editor.is-focused)
     -5:36.6.0 core:close (atom-text-editor.editor.mini.is-focused)
     -5:34.5.0 settings-view:open (atom-text-editor.editor.is-focused)
  2x -5:31 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:55 application:open-your-keymap (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -4:07.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.13.2
highlight-selected, v0.11.2
linter, v1.11.4
linter-eslint, vundefined
minimap, v4.21.0
minimap-highlight-selected, v4.4.0
open-recent, v5.0.0

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by nathansobo**
Also, send assertion failures back to bugsnag when this happens.

Fixes #766

### CODE REVIEW

File: lib/package-card.coffee [hunk 1]
```diff
@@ -467,10 +467,20 @@ class PackageCard extends View
...
+        atom.assert false, "Package update failed", (assertionError) =>
+          assertionError.metadata = {
+            type: @type,
+            name: pack.name,
+            version: version,
+            errorMessage: error.message,
+            errorStack: error.stack,
+            errorStderr: error.stderr
+          }
+        console.error("Updating #{@type} #{pack.name} to #{version} failed:\n", error, error.stderr ? '')
```
Comment (50Wliu) [inline lib/package-card.coffee]: Should this be a notification instead?

Comment (50Wliu) [inline lib/package-card.coffee]: Ah, I didn't notice that it was already a console.error beforehand.
